version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    volumes:
      - anonrate_local_postgres:/var/lib/postgresql/data
      - anonrate_local_postgres_backups:/backups
    ports: 
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres

volumes: 
  anonrate_local_postgres: {}
  anonrate_local_postgres_backups: {}