# Generated by Django 4.0.3 on 2022-08-10 22:28

import apps.user.models
from django.db import migrations
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.user.models.avatar_location),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+393383838338", max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
    ]
