# Generated by Django 4.0.3 on 2022-08-13 10:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_label'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='SMSVerification',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('security_code', models.CharField(max_length=120, verbose_name='Security Code')),
    #             ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
    #             ('session_token', models.CharField(max_length=500, verbose_name='Device Session Token')),
    #             ('is_verified', models.BooleanField(default=False, verbose_name='Security Code Verified')),
    #             ('created_at', models.DateTimeField(auto_now_add=True)),
    #             ('modified_at', models.DateTimeField(auto_now=True)),
    #         ],
    #         options={
    #             'verbose_name': 'SMS Verification',
    #             'verbose_name_plural': 'SMS Verifications',
    #             'db_table': 'sms_verification',
    #             'ordering': ('-modified_at',),
    #             'unique_together': {('security_code', 'phone_number', 'session_token')},
    #         },
    #     ),
    # ]
