# Generated by Django 4.0.3 on 2022-08-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_smsverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
